#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 139
#define LARGE_STATE_COUNT 4
#define SYMBOL_COUNT 41
#define ALIAS_COUNT 0
#define TOKEN_COUNT 19
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 6
#define PRODUCTION_ID_COUNT 15

enum {
  anon_sym_EQ = 1,
  anon_sym_PLUS = 2,
  anon_sym_STAR = 3,
  aux_sym_comment_token1 = 4,
  anon_sym_def = 5,
  anon_sym_LPAREN = 6,
  anon_sym_RPAREN = 7,
  anon_sym_COMMA = 8,
  sym_identifier = 9,
  anon_sym_LBRACK = 10,
  anon_sym_RBRACK = 11,
  anon_sym_COLON = 12,
  sym_integer = 13,
  anon_sym_LBRACE = 14,
  anon_sym_RBRACE = 15,
  anon_sym_steps = 16,
  anon_sym_DQUOTE = 17,
  aux_sym_string_token1 = 18,
  sym_source_file = 19,
  sym_statement = 20,
  sym_assignment = 21,
  sym__binary_op = 22,
  sym_comment = 23,
  sym_declaration = 24,
  sym_expression = 25,
  sym_function_call = 26,
  sym_index = 27,
  sym_list = 28,
  sym__map_item = 29,
  sym_map = 30,
  sym_pipeline_block = 31,
  sym_step = 32,
  sym_string = 33,
  sym__type = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_function_call_repeat1 = 36,
  aux_sym_list_repeat1 = 37,
  aux_sym_map_repeat1 = 38,
  aux_sym_pipeline_block_repeat1 = 39,
  aux_sym_pipeline_block_repeat2 = 40,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_EQ] = "=",
  [anon_sym_PLUS] = "+",
  [anon_sym_STAR] = "*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_def] = "def",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_COMMA] = ",",
  [sym_identifier] = "identifier",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [anon_sym_COLON] = ":",
  [sym_integer] = "integer",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_steps] = "steps",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [sym_source_file] = "source_file",
  [sym_statement] = "statement",
  [sym_assignment] = "assignment",
  [sym__binary_op] = "_binary_op",
  [sym_comment] = "comment",
  [sym_declaration] = "declaration",
  [sym_expression] = "expression",
  [sym_function_call] = "function_call",
  [sym_index] = "index",
  [sym_list] = "list",
  [sym__map_item] = "_map_item",
  [sym_map] = "map",
  [sym_pipeline_block] = "pipeline_block",
  [sym_step] = "step",
  [sym_string] = "string",
  [sym__type] = "_type",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_function_call_repeat1] = "function_call_repeat1",
  [aux_sym_list_repeat1] = "list_repeat1",
  [aux_sym_map_repeat1] = "map_repeat1",
  [aux_sym_pipeline_block_repeat1] = "pipeline_block_repeat1",
  [aux_sym_pipeline_block_repeat2] = "pipeline_block_repeat2",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_def] = anon_sym_def,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [sym_identifier] = sym_identifier,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [anon_sym_COLON] = anon_sym_COLON,
  [sym_integer] = sym_integer,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_steps] = anon_sym_steps,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [sym_source_file] = sym_source_file,
  [sym_statement] = sym_statement,
  [sym_assignment] = sym_assignment,
  [sym__binary_op] = sym__binary_op,
  [sym_comment] = sym_comment,
  [sym_declaration] = sym_declaration,
  [sym_expression] = sym_expression,
  [sym_function_call] = sym_function_call,
  [sym_index] = sym_index,
  [sym_list] = sym_list,
  [sym__map_item] = sym__map_item,
  [sym_map] = sym_map,
  [sym_pipeline_block] = sym_pipeline_block,
  [sym_step] = sym_step,
  [sym_string] = sym_string,
  [sym__type] = sym__type,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_function_call_repeat1] = aux_sym_function_call_repeat1,
  [aux_sym_list_repeat1] = aux_sym_list_repeat1,
  [aux_sym_map_repeat1] = aux_sym_map_repeat1,
  [aux_sym_pipeline_block_repeat1] = aux_sym_pipeline_block_repeat1,
  [aux_sym_pipeline_block_repeat2] = aux_sym_pipeline_block_repeat2,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_def] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_steps] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym__binary_op] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_function_call] = {
    .visible = true,
    .named = true,
  },
  [sym_index] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__map_item] = {
    .visible = false,
    .named = true,
  },
  [sym_map] = {
    .visible = true,
    .named = true,
  },
  [sym_pipeline_block] = {
    .visible = true,
    .named = true,
  },
  [sym_step] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym__type] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_function_call_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_map_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_pipeline_block_repeat2] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_args = 1,
  field_function = 2,
  field_key = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_args] = "args",
  [field_function] = "function",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 4},
  [5] = {.index = 9, .length = 2},
  [6] = {.index = 11, .length = 4},
  [7] = {.index = 15, .length = 2},
  [8] = {.index = 17, .length = 4},
  [9] = {.index = 21, .length = 3},
  [10] = {.index = 24, .length = 5},
  [11] = {.index = 29, .length = 7},
  [12] = {.index = 36, .length = 6},
  [13] = {.index = 42, .length = 8},
  [14] = {.index = 50, .length = 4},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_function, 0},
  [1] =
    {field_key, 0, .inherited = true},
    {field_value, 0, .inherited = true},
  [3] =
    {field_key, 1, .inherited = true},
    {field_value, 1, .inherited = true},
  [5] =
    {field_key, 0, .inherited = true},
    {field_key, 1, .inherited = true},
    {field_value, 0, .inherited = true},
    {field_value, 1, .inherited = true},
  [9] =
    {field_args, 2},
    {field_function, 0},
  [11] =
    {field_args, 2},
    {field_function, 0},
    {field_key, 2, .inherited = true},
    {field_value, 2, .inherited = true},
  [15] =
    {field_key, 0},
    {field_value, 2},
  [17] =
    {field_key, 1, .inherited = true},
    {field_key, 2, .inherited = true},
    {field_value, 1, .inherited = true},
    {field_value, 2, .inherited = true},
  [21] =
    {field_args, 2},
    {field_args, 3},
    {field_function, 0},
  [24] =
    {field_args, 2},
    {field_args, 3},
    {field_function, 0},
    {field_key, 2, .inherited = true},
    {field_value, 2, .inherited = true},
  [29] =
    {field_args, 2},
    {field_args, 3},
    {field_function, 0},
    {field_key, 2, .inherited = true},
    {field_key, 3, .inherited = true},
    {field_value, 2, .inherited = true},
    {field_value, 3, .inherited = true},
  [36] =
    {field_args, 2},
    {field_args, 3},
    {field_args, 4},
    {field_function, 0},
    {field_key, 2, .inherited = true},
    {field_value, 2, .inherited = true},
  [42] =
    {field_args, 2},
    {field_args, 3},
    {field_args, 4},
    {field_function, 0},
    {field_key, 2, .inherited = true},
    {field_key, 3, .inherited = true},
    {field_value, 2, .inherited = true},
    {field_value, 3, .inherited = true},
  [50] =
    {field_key, 0},
    {field_key, 1},
    {field_key, 2},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 4,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 22,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 27,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 31,
  [38] = 32,
  [39] = 39,
  [40] = 39,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 58,
  [64] = 57,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 21,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 72,
  [74] = 74,
  [75] = 71,
  [76] = 76,
  [77] = 11,
  [78] = 78,
  [79] = 10,
  [80] = 9,
  [81] = 15,
  [82] = 82,
  [83] = 83,
  [84] = 18,
  [85] = 85,
  [86] = 19,
  [87] = 12,
  [88] = 25,
  [89] = 89,
  [90] = 16,
  [91] = 17,
  [92] = 14,
  [93] = 76,
  [94] = 20,
  [95] = 24,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 99,
  [104] = 104,
  [105] = 96,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 98,
  [112] = 101,
  [113] = 113,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 120,
  [121] = 117,
  [122] = 122,
  [123] = 118,
  [124] = 124,
  [125] = 125,
  [126] = 126,
  [127] = 127,
  [128] = 127,
  [129] = 129,
  [130] = 130,
  [131] = 131,
  [132] = 132,
  [133] = 133,
  [134] = 134,
  [135] = 125,
  [136] = 136,
  [137] = 137,
  [138] = 138,
};

static inline bool sym_identifier_character_set_1(int32_t c) {
  return (c < 192
    ? (c < '_'
      ? (c < 'A'
        ? c == '$'
        : c <= 'Z')
      : (c <= '_' || (c >= 'a' && c <= 'z')))
    : (c <= 214 || (c < 256
      ? (c < 248
        ? (c >= 216 && c <= 246)
        : c <= 248)
      : (c <= 55295 || (c >= 57344 && c <= 65534)))));
}

static inline bool sym_identifier_character_set_2(int32_t c) {
  return (c < 192
    ? (c < 'A'
      ? (c < '0'
        ? c == '$'
        : c <= '9')
      : (c <= 'Z' || (c < 'a'
        ? c == '_'
        : c <= 'z')))
    : (c <= 214 || (c < 256
      ? (c < 248
        ? (c >= 216 && c <= 246)
        : c <= 248)
      : (c <= 55295 || (c >= 57344 && c <= 65534)))));
}

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(5);
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == ',') ADVANCE(14);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == ':') ADVANCE(24);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == 'd') ADVANCE(15);
      if (lookahead == 's') ADVANCE(20);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(0)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (sym_identifier_character_set_1(lookahead)) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(29);
      if (lookahead == '(') ADVANCE(12);
      if (lookahead == ')') ADVANCE(13);
      if (lookahead == '*') ADVANCE(8);
      if (lookahead == '+') ADVANCE(7);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == '=') ADVANCE(6);
      if (lookahead == '[') ADVANCE(22);
      if (lookahead == ']') ADVANCE(23);
      if (lookahead == '{') ADVANCE(26);
      if (lookahead == '}') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      if (sym_identifier_character_set_1(lookahead)) ADVANCE(21);
      END_STATE();
    case 2:
      if (lookahead == '/') ADVANCE(10);
      END_STATE();
    case 3:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 4:
      if (eof) ADVANCE(5);
      if (lookahead == '/') ADVANCE(2);
      if (lookahead == 's') ADVANCE(20);
      if (lookahead == '}') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(4)
      if (sym_identifier_character_set_1(lookahead)) ADVANCE(21);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(anon_sym_PLUS);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '\n') ADVANCE(32);
      if (lookahead == '"') ADVANCE(10);
      if (lookahead != 0) ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_def);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(17);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(18);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'f') ADVANCE(11);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'p') ADVANCE(19);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(28);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 't') ADVANCE(16);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_identifier);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_steps);
      if (sym_identifier_character_set_2(lookahead)) ADVANCE(21);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(31);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(30);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(9);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(32);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 1},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 1},
  [32] = {.lex_state = 1},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 1},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 1},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 1},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 1},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 1},
  [70] = {.lex_state = 4},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 1},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 1},
  [81] = {.lex_state = 1},
  [82] = {.lex_state = 4},
  [83] = {.lex_state = 4},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 1},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 1},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 1},
  [95] = {.lex_state = 1},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 0},
  [100] = {.lex_state = 1},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 4},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 4},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 1},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 1},
  [113] = {.lex_state = 1},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 4},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 1},
  [120] = {.lex_state = 0},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 30},
  [126] = {.lex_state = 0},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 0},
  [135] = {.lex_state = 30},
  [136] = {.lex_state = 0},
  [137] = {.lex_state = 1},
  [138] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_COMMA] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [sym_integer] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_steps] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(134),
    [sym_statement] = STATE(45),
    [sym_assignment] = STATE(46),
    [sym__binary_op] = STATE(20),
    [sym_comment] = STATE(1),
    [sym_declaration] = STATE(46),
    [sym_expression] = STATE(115),
    [sym_function_call] = STATE(46),
    [sym_index] = STATE(107),
    [sym_list] = STATE(20),
    [sym_map] = STATE(20),
    [sym_pipeline_block] = STATE(131),
    [sym_string] = STATE(20),
    [sym__type] = STATE(137),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_integer] = ACTIONS(15),
    [anon_sym_steps] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
  },
  [2] = {
    [sym_statement] = STATE(45),
    [sym_assignment] = STATE(46),
    [sym__binary_op] = STATE(20),
    [sym_comment] = STATE(2),
    [sym_declaration] = STATE(46),
    [sym_expression] = STATE(115),
    [sym_function_call] = STATE(46),
    [sym_index] = STATE(107),
    [sym_list] = STATE(20),
    [sym_map] = STATE(20),
    [sym_pipeline_block] = STATE(136),
    [sym_string] = STATE(20),
    [sym__type] = STATE(137),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(21),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(7),
    [anon_sym_LPAREN] = ACTIONS(9),
    [sym_identifier] = ACTIONS(11),
    [anon_sym_LBRACK] = ACTIONS(13),
    [sym_integer] = ACTIONS(15),
    [anon_sym_steps] = ACTIONS(17),
    [anon_sym_DQUOTE] = ACTIONS(19),
  },
  [3] = {
    [sym_statement] = STATE(45),
    [sym_assignment] = STATE(46),
    [sym__binary_op] = STATE(20),
    [sym_comment] = STATE(3),
    [sym_declaration] = STATE(46),
    [sym_expression] = STATE(115),
    [sym_function_call] = STATE(46),
    [sym_index] = STATE(107),
    [sym_list] = STATE(20),
    [sym_map] = STATE(20),
    [sym_string] = STATE(20),
    [sym__type] = STATE(137),
    [aux_sym_source_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [aux_sym_comment_token1] = ACTIONS(3),
    [anon_sym_def] = ACTIONS(25),
    [anon_sym_LPAREN] = ACTIONS(28),
    [sym_identifier] = ACTIONS(31),
    [anon_sym_LBRACK] = ACTIONS(34),
    [sym_integer] = ACTIONS(37),
    [anon_sym_steps] = ACTIONS(40),
    [anon_sym_DQUOTE] = ACTIONS(42),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(49), 1,
      anon_sym_RBRACK,
    STATE(4), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym_list_repeat1,
    STATE(73), 1,
      aux_sym_map_repeat1,
    STATE(93), 1,
      sym_expression,
    STATE(118), 1,
      sym__map_item,
    ACTIONS(47), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [42] = 12,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(51), 1,
      anon_sym_RBRACK,
    STATE(5), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym_list_repeat1,
    STATE(72), 1,
      aux_sym_map_repeat1,
    STATE(76), 1,
      sym_expression,
    STATE(123), 1,
      sym__map_item,
    ACTIONS(47), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [84] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(53), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      anon_sym_RPAREN,
    ACTIONS(61), 1,
      anon_sym_LBRACK,
    ACTIONS(64), 1,
      anon_sym_DQUOTE,
    STATE(97), 1,
      sym_expression,
    STATE(130), 1,
      sym__map_item,
    ACTIONS(58), 2,
      sym_identifier,
      sym_integer,
    STATE(6), 2,
      sym_comment,
      aux_sym_function_call_repeat1,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [121] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(67), 1,
      anon_sym_RPAREN,
    STATE(6), 1,
      aux_sym_function_call_repeat1,
    STATE(7), 1,
      sym_comment,
    STATE(78), 1,
      sym_expression,
    STATE(122), 1,
      sym__map_item,
    ACTIONS(47), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [160] = 11,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(45), 1,
      anon_sym_LPAREN,
    ACTIONS(69), 1,
      anon_sym_RPAREN,
    STATE(7), 1,
      aux_sym_function_call_repeat1,
    STATE(8), 1,
      sym_comment,
    STATE(85), 1,
      sym_expression,
    STATE(120), 1,
      sym__map_item,
    ACTIONS(47), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [199] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(9), 1,
      sym_comment,
    ACTIONS(73), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(71), 11,
      ts_builtin_sym_end,
      anon_sym_EQ,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [224] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(10), 1,
      sym_comment,
    ACTIONS(77), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(75), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [248] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(11), 1,
      sym_comment,
    ACTIONS(81), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(79), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [272] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    STATE(12), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(83), 9,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [298] = 9,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(89), 1,
      anon_sym_LPAREN,
    ACTIONS(95), 1,
      anon_sym_LBRACK,
    ACTIONS(98), 1,
      anon_sym_RBRACK,
    ACTIONS(100), 1,
      anon_sym_DQUOTE,
    STATE(109), 1,
      sym_expression,
    ACTIONS(92), 2,
      sym_identifier,
      sym_integer,
    STATE(13), 2,
      sym_comment,
      aux_sym_list_repeat1,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [332] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(14), 1,
      sym_comment,
    ACTIONS(105), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(103), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [356] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(15), 1,
      sym_comment,
    ACTIONS(109), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(107), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [380] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(16), 1,
      sym_comment,
    ACTIONS(113), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(111), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [404] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(17), 1,
      sym_comment,
    ACTIONS(117), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(115), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [428] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(18), 1,
      sym_comment,
    ACTIONS(121), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(119), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [452] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(19), 1,
      sym_comment,
    ACTIONS(87), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(83), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [476] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(20), 1,
      sym_comment,
    ACTIONS(125), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(123), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [500] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(21), 1,
      sym_comment,
    ACTIONS(129), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(127), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [524] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      aux_sym_list_repeat1,
    STATE(22), 1,
      sym_comment,
    STATE(71), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [560] = 10,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
    STATE(13), 1,
      aux_sym_list_repeat1,
    STATE(23), 1,
      sym_comment,
    STATE(75), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [596] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(24), 1,
      sym_comment,
    ACTIONS(137), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(135), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [620] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(25), 1,
      sym_comment,
    ACTIONS(141), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(139), 10,
      ts_builtin_sym_end,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [644] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(26), 1,
      sym_comment,
    STATE(104), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [674] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(27), 1,
      sym_comment,
    STATE(99), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [704] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(28), 1,
      sym_comment,
    STATE(110), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [734] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(29), 1,
      sym_comment,
    STATE(65), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [764] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    STATE(30), 1,
      sym_comment,
    STATE(89), 1,
      sym_expression,
    ACTIONS(145), 2,
      sym_identifier,
      sym_integer,
    STATE(94), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [794] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(12), 1,
      sym_expression,
    STATE(31), 1,
      sym_comment,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [824] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(19), 1,
      sym_expression,
    STATE(32), 1,
      sym_comment,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [854] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(33), 1,
      sym_comment,
    STATE(103), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [884] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(34), 1,
      sym_comment,
    STATE(41), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [914] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(35), 1,
      sym_comment,
    STATE(42), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [944] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(36), 1,
      sym_comment,
    STATE(59), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [974] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    STATE(37), 1,
      sym_comment,
    STATE(87), 1,
      sym_expression,
    ACTIONS(145), 2,
      sym_identifier,
      sym_integer,
    STATE(94), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [1004] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(143), 1,
      anon_sym_LPAREN,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      anon_sym_DQUOTE,
    STATE(38), 1,
      sym_comment,
    STATE(86), 1,
      sym_expression,
    ACTIONS(145), 2,
      sym_identifier,
      sym_integer,
    STATE(94), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [1034] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(39), 1,
      sym_comment,
    STATE(96), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [1064] = 8,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(9), 1,
      anon_sym_LPAREN,
    ACTIONS(13), 1,
      anon_sym_LBRACK,
    ACTIONS(19), 1,
      anon_sym_DQUOTE,
    STATE(40), 1,
      sym_comment,
    STATE(105), 1,
      sym_expression,
    ACTIONS(15), 2,
      sym_identifier,
      sym_integer,
    STATE(20), 5,
      sym__binary_op,
      sym_index,
      sym_list,
      sym_map,
      sym_string,
  [1094] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(41), 1,
      sym_comment,
    ACTIONS(155), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(151), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_integer,
      anon_sym_DQUOTE,
  [1121] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(42), 1,
      sym_comment,
    ACTIONS(161), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(159), 4,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      sym_integer,
      anon_sym_DQUOTE,
  [1148] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(165), 1,
      anon_sym_EQ,
    STATE(43), 1,
      sym_comment,
    ACTIONS(167), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1170] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(44), 1,
      sym_comment,
    ACTIONS(171), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(169), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1189] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(45), 1,
      sym_comment,
    ACTIONS(175), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(173), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1208] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(46), 1,
      sym_comment,
    ACTIONS(179), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(177), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1227] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(47), 1,
      sym_comment,
    ACTIONS(183), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(181), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1246] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(48), 1,
      sym_comment,
    ACTIONS(187), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(185), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1265] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(49), 1,
      sym_comment,
    ACTIONS(191), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(189), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1284] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(50), 1,
      sym_comment,
    ACTIONS(195), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1303] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(51), 1,
      sym_comment,
    ACTIONS(195), 3,
      anon_sym_def,
      sym_identifier,
      anon_sym_steps,
    ACTIONS(193), 5,
      ts_builtin_sym_end,
      anon_sym_LPAREN,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1322] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(197), 1,
      anon_sym_COLON,
    STATE(52), 1,
      sym_comment,
    ACTIONS(103), 6,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1340] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(199), 1,
      anon_sym_EQ,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      sym_identifier,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    STATE(53), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACK,
  [1364] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(207), 1,
      anon_sym_COLON,
    STATE(54), 1,
      sym_comment,
    ACTIONS(123), 6,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
  [1382] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(55), 1,
      sym_comment,
    ACTIONS(209), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1397] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(56), 1,
      sym_comment,
    ACTIONS(211), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1412] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(213), 1,
      anon_sym_RBRACK,
    STATE(57), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1429] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    STATE(58), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1446] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(59), 1,
      sym_comment,
    ACTIONS(217), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1467] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(60), 1,
      sym_comment,
    ACTIONS(211), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1482] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(61), 1,
      sym_comment,
    ACTIONS(209), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1497] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(62), 1,
      sym_comment,
    ACTIONS(98), 6,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1512] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    STATE(63), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1529] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(221), 1,
      anon_sym_RBRACK,
    STATE(64), 1,
      sym_comment,
    ACTIONS(98), 5,
      anon_sym_LPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1546] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(65), 1,
      sym_comment,
    ACTIONS(223), 3,
      anon_sym_RPAREN,
      anon_sym_COMMA,
      anon_sym_RBRACK,
  [1567] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(199), 1,
      anon_sym_EQ,
    ACTIONS(201), 1,
      anon_sym_LPAREN,
    ACTIONS(203), 1,
      sym_identifier,
    STATE(66), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACK,
  [1588] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(67), 1,
      sym_comment,
    ACTIONS(209), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1603] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(68), 1,
      sym_comment,
    ACTIONS(211), 6,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
      anon_sym_LBRACK,
      sym_integer,
      anon_sym_DQUOTE,
  [1618] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(69), 1,
      sym_comment,
    ACTIONS(127), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1632] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(17), 1,
      anon_sym_steps,
    ACTIONS(225), 1,
      sym_identifier,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      sym_comment,
    STATE(82), 1,
      aux_sym_pipeline_block_repeat1,
    STATE(116), 1,
      sym_pipeline_block,
  [1654] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(219), 1,
      anon_sym_RBRACK,
    ACTIONS(229), 1,
      anon_sym_COMMA,
    STATE(71), 1,
      sym_comment,
  [1676] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    STATE(72), 1,
      sym_comment,
    STATE(74), 1,
      aux_sym_map_repeat1,
    STATE(121), 1,
      sym__map_item,
    ACTIONS(233), 2,
      sym_identifier,
      sym_integer,
  [1696] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(231), 1,
      anon_sym_LPAREN,
    STATE(73), 1,
      sym_comment,
    STATE(74), 1,
      aux_sym_map_repeat1,
    STATE(117), 1,
      sym__map_item,
    ACTIONS(233), 2,
      sym_identifier,
      sym_integer,
  [1716] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(235), 1,
      anon_sym_LPAREN,
    STATE(126), 1,
      sym__map_item,
    ACTIONS(238), 2,
      sym_identifier,
      sym_integer,
    STATE(74), 2,
      sym_comment,
      aux_sym_map_repeat1,
  [1734] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(215), 1,
      anon_sym_RBRACK,
    ACTIONS(241), 1,
      anon_sym_COMMA,
    STATE(75), 1,
      sym_comment,
  [1756] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(133), 1,
      anon_sym_RBRACK,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(243), 1,
      anon_sym_COMMA,
    STATE(76), 1,
      sym_comment,
  [1778] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(77), 1,
      sym_comment,
    ACTIONS(79), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1792] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(245), 1,
      anon_sym_RPAREN,
    ACTIONS(247), 1,
      anon_sym_COMMA,
    STATE(78), 1,
      sym_comment,
  [1814] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(79), 1,
      sym_comment,
    ACTIONS(75), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1828] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(80), 1,
      sym_comment,
    ACTIONS(71), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1842] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(81), 1,
      sym_comment,
    ACTIONS(107), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1856] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(249), 1,
      sym_identifier,
    ACTIONS(252), 1,
      anon_sym_RBRACE,
    ACTIONS(254), 1,
      anon_sym_steps,
    STATE(116), 1,
      sym_pipeline_block,
    STATE(82), 2,
      sym_comment,
      aux_sym_pipeline_block_repeat1,
  [1876] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(17), 1,
      anon_sym_steps,
    ACTIONS(225), 1,
      sym_identifier,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    STATE(70), 1,
      aux_sym_pipeline_block_repeat1,
    STATE(83), 1,
      sym_comment,
    STATE(116), 1,
      sym_pipeline_block,
  [1898] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(84), 1,
      sym_comment,
    ACTIONS(119), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1912] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(259), 1,
      anon_sym_RPAREN,
    ACTIONS(261), 1,
      anon_sym_COMMA,
    STATE(85), 1,
      sym_comment,
  [1934] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(86), 1,
      sym_comment,
    ACTIONS(83), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1948] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(263), 1,
      anon_sym_STAR,
    STATE(87), 1,
      sym_comment,
    ACTIONS(83), 4,
      anon_sym_PLUS,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1964] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(88), 1,
      sym_comment,
    ACTIONS(139), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [1978] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(263), 1,
      anon_sym_STAR,
    ACTIONS(265), 1,
      anon_sym_PLUS,
    ACTIONS(269), 1,
      anon_sym_LBRACK,
    STATE(89), 1,
      sym_comment,
    ACTIONS(267), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [1998] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(90), 1,
      sym_comment,
    ACTIONS(111), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [2012] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(91), 1,
      sym_comment,
    ACTIONS(115), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [2026] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(92), 1,
      sym_comment,
    ACTIONS(103), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [2040] = 7,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(131), 1,
      anon_sym_RBRACK,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(271), 1,
      anon_sym_COMMA,
    STATE(93), 1,
      sym_comment,
  [2062] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(94), 1,
      sym_comment,
    ACTIONS(123), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [2076] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(95), 1,
      sym_comment,
    ACTIONS(135), 5,
      anon_sym_PLUS,
      anon_sym_STAR,
      sym_identifier,
      anon_sym_LBRACK,
      anon_sym_RBRACE,
  [2090] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(273), 1,
      anon_sym_RPAREN,
    STATE(96), 1,
      sym_comment,
  [2109] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(275), 1,
      anon_sym_COMMA,
    STATE(97), 1,
      sym_comment,
  [2128] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(279), 1,
      anon_sym_RBRACK,
    STATE(98), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [2143] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(281), 1,
      anon_sym_RBRACK,
    STATE(99), 1,
      sym_comment,
  [2162] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(227), 1,
      anon_sym_RBRACE,
    ACTIONS(283), 1,
      sym_identifier,
    STATE(100), 1,
      sym_comment,
    STATE(113), 1,
      aux_sym_pipeline_block_repeat2,
    STATE(119), 1,
      sym_step,
  [2181] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(285), 1,
      anon_sym_RBRACK,
    STATE(101), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [2196] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(102), 1,
      sym_comment,
    ACTIONS(287), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(289), 2,
      sym_identifier,
      anon_sym_steps,
  [2211] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(291), 1,
      anon_sym_RBRACK,
    STATE(103), 1,
      sym_comment,
  [2230] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(293), 1,
      anon_sym_RPAREN,
    STATE(104), 1,
      sym_comment,
  [2249] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(295), 1,
      anon_sym_RPAREN,
    STATE(105), 1,
      sym_comment,
  [2268] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(106), 1,
      sym_comment,
    ACTIONS(297), 2,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
    ACTIONS(299), 2,
      sym_identifier,
      anon_sym_steps,
  [2283] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(199), 1,
      anon_sym_EQ,
    STATE(107), 1,
      sym_comment,
    ACTIONS(123), 3,
      anon_sym_PLUS,
      anon_sym_STAR,
      anon_sym_LBRACK,
  [2298] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(257), 1,
      anon_sym_RBRACE,
    ACTIONS(283), 1,
      sym_identifier,
    STATE(100), 1,
      aux_sym_pipeline_block_repeat2,
    STATE(108), 1,
      sym_comment,
    STATE(119), 1,
      sym_step,
  [2317] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(301), 1,
      anon_sym_COMMA,
    STATE(109), 1,
      sym_comment,
  [2336] = 6,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    ACTIONS(303), 1,
      anon_sym_RPAREN,
    STATE(110), 1,
      sym_comment,
  [2355] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(305), 1,
      anon_sym_RBRACK,
    STATE(111), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [2370] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(307), 1,
      anon_sym_RBRACK,
    STATE(112), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [2385] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(309), 1,
      sym_identifier,
    ACTIONS(312), 1,
      anon_sym_RBRACE,
    STATE(119), 1,
      sym_step,
    STATE(113), 2,
      sym_comment,
      aux_sym_pipeline_block_repeat2,
  [2402] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(114), 1,
      sym_comment,
    ACTIONS(277), 3,
      anon_sym_LPAREN,
      sym_identifier,
      sym_integer,
  [2414] = 5,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(85), 1,
      anon_sym_STAR,
    ACTIONS(153), 1,
      anon_sym_PLUS,
    ACTIONS(157), 1,
      anon_sym_LBRACK,
    STATE(115), 1,
      sym_comment,
  [2430] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(316), 1,
      anon_sym_RBRACE,
    STATE(116), 1,
      sym_comment,
    ACTIONS(314), 2,
      sym_identifier,
      anon_sym_steps,
  [2444] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(318), 1,
      anon_sym_COMMA,
    ACTIONS(320), 1,
      anon_sym_RBRACK,
    STATE(117), 1,
      sym_comment,
  [2457] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(322), 1,
      anon_sym_COMMA,
    ACTIONS(324), 1,
      anon_sym_RBRACK,
    STATE(118), 1,
      sym_comment,
  [2470] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    STATE(119), 1,
      sym_comment,
    ACTIONS(326), 2,
      sym_identifier,
      anon_sym_RBRACE,
  [2481] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(328), 1,
      anon_sym_RPAREN,
    ACTIONS(330), 1,
      anon_sym_COMMA,
    STATE(120), 1,
      sym_comment,
  [2494] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(332), 1,
      anon_sym_COMMA,
    ACTIONS(334), 1,
      anon_sym_RBRACK,
    STATE(121), 1,
      sym_comment,
  [2507] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    ACTIONS(338), 1,
      anon_sym_COMMA,
    STATE(122), 1,
      sym_comment,
  [2520] = 4,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(340), 1,
      anon_sym_COMMA,
    ACTIONS(342), 1,
      anon_sym_RBRACK,
    STATE(123), 1,
      sym_comment,
  [2533] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(344), 1,
      anon_sym_LBRACE,
    STATE(124), 1,
      sym_comment,
  [2543] = 3,
    ACTIONS(346), 1,
      aux_sym_comment_token1,
    ACTIONS(348), 1,
      aux_sym_string_token1,
    STATE(125), 1,
      sym_comment,
  [2553] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(350), 1,
      anon_sym_COMMA,
    STATE(126), 1,
      sym_comment,
  [2563] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(352), 1,
      anon_sym_DQUOTE,
    STATE(127), 1,
      sym_comment,
  [2573] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(354), 1,
      anon_sym_DQUOTE,
    STATE(128), 1,
      sym_comment,
  [2583] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(197), 1,
      anon_sym_COLON,
    STATE(129), 1,
      sym_comment,
  [2593] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(356), 1,
      anon_sym_COMMA,
    STATE(130), 1,
      sym_comment,
  [2603] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(21), 1,
      ts_builtin_sym_end,
    STATE(131), 1,
      sym_comment,
  [2613] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(205), 1,
      anon_sym_LBRACE,
    STATE(132), 1,
      sym_comment,
  [2623] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(207), 1,
      anon_sym_COLON,
    STATE(133), 1,
      sym_comment,
  [2633] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(358), 1,
      ts_builtin_sym_end,
    STATE(134), 1,
      sym_comment,
  [2643] = 3,
    ACTIONS(346), 1,
      aux_sym_comment_token1,
    ACTIONS(360), 1,
      aux_sym_string_token1,
    STATE(135), 1,
      sym_comment,
  [2653] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(362), 1,
      ts_builtin_sym_end,
    STATE(136), 1,
      sym_comment,
  [2663] = 3,
    ACTIONS(3), 1,
      aux_sym_comment_token1,
    ACTIONS(364), 1,
      sym_identifier,
    STATE(137), 1,
      sym_comment,
  [2673] = 1,
    ACTIONS(366), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(4)] = 0,
  [SMALL_STATE(5)] = 42,
  [SMALL_STATE(6)] = 84,
  [SMALL_STATE(7)] = 121,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 199,
  [SMALL_STATE(10)] = 224,
  [SMALL_STATE(11)] = 248,
  [SMALL_STATE(12)] = 272,
  [SMALL_STATE(13)] = 298,
  [SMALL_STATE(14)] = 332,
  [SMALL_STATE(15)] = 356,
  [SMALL_STATE(16)] = 380,
  [SMALL_STATE(17)] = 404,
  [SMALL_STATE(18)] = 428,
  [SMALL_STATE(19)] = 452,
  [SMALL_STATE(20)] = 476,
  [SMALL_STATE(21)] = 500,
  [SMALL_STATE(22)] = 524,
  [SMALL_STATE(23)] = 560,
  [SMALL_STATE(24)] = 596,
  [SMALL_STATE(25)] = 620,
  [SMALL_STATE(26)] = 644,
  [SMALL_STATE(27)] = 674,
  [SMALL_STATE(28)] = 704,
  [SMALL_STATE(29)] = 734,
  [SMALL_STATE(30)] = 764,
  [SMALL_STATE(31)] = 794,
  [SMALL_STATE(32)] = 824,
  [SMALL_STATE(33)] = 854,
  [SMALL_STATE(34)] = 884,
  [SMALL_STATE(35)] = 914,
  [SMALL_STATE(36)] = 944,
  [SMALL_STATE(37)] = 974,
  [SMALL_STATE(38)] = 1004,
  [SMALL_STATE(39)] = 1034,
  [SMALL_STATE(40)] = 1064,
  [SMALL_STATE(41)] = 1094,
  [SMALL_STATE(42)] = 1121,
  [SMALL_STATE(43)] = 1148,
  [SMALL_STATE(44)] = 1170,
  [SMALL_STATE(45)] = 1189,
  [SMALL_STATE(46)] = 1208,
  [SMALL_STATE(47)] = 1227,
  [SMALL_STATE(48)] = 1246,
  [SMALL_STATE(49)] = 1265,
  [SMALL_STATE(50)] = 1284,
  [SMALL_STATE(51)] = 1303,
  [SMALL_STATE(52)] = 1322,
  [SMALL_STATE(53)] = 1340,
  [SMALL_STATE(54)] = 1364,
  [SMALL_STATE(55)] = 1382,
  [SMALL_STATE(56)] = 1397,
  [SMALL_STATE(57)] = 1412,
  [SMALL_STATE(58)] = 1429,
  [SMALL_STATE(59)] = 1446,
  [SMALL_STATE(60)] = 1467,
  [SMALL_STATE(61)] = 1482,
  [SMALL_STATE(62)] = 1497,
  [SMALL_STATE(63)] = 1512,
  [SMALL_STATE(64)] = 1529,
  [SMALL_STATE(65)] = 1546,
  [SMALL_STATE(66)] = 1567,
  [SMALL_STATE(67)] = 1588,
  [SMALL_STATE(68)] = 1603,
  [SMALL_STATE(69)] = 1618,
  [SMALL_STATE(70)] = 1632,
  [SMALL_STATE(71)] = 1654,
  [SMALL_STATE(72)] = 1676,
  [SMALL_STATE(73)] = 1696,
  [SMALL_STATE(74)] = 1716,
  [SMALL_STATE(75)] = 1734,
  [SMALL_STATE(76)] = 1756,
  [SMALL_STATE(77)] = 1778,
  [SMALL_STATE(78)] = 1792,
  [SMALL_STATE(79)] = 1814,
  [SMALL_STATE(80)] = 1828,
  [SMALL_STATE(81)] = 1842,
  [SMALL_STATE(82)] = 1856,
  [SMALL_STATE(83)] = 1876,
  [SMALL_STATE(84)] = 1898,
  [SMALL_STATE(85)] = 1912,
  [SMALL_STATE(86)] = 1934,
  [SMALL_STATE(87)] = 1948,
  [SMALL_STATE(88)] = 1964,
  [SMALL_STATE(89)] = 1978,
  [SMALL_STATE(90)] = 1998,
  [SMALL_STATE(91)] = 2012,
  [SMALL_STATE(92)] = 2026,
  [SMALL_STATE(93)] = 2040,
  [SMALL_STATE(94)] = 2062,
  [SMALL_STATE(95)] = 2076,
  [SMALL_STATE(96)] = 2090,
  [SMALL_STATE(97)] = 2109,
  [SMALL_STATE(98)] = 2128,
  [SMALL_STATE(99)] = 2143,
  [SMALL_STATE(100)] = 2162,
  [SMALL_STATE(101)] = 2181,
  [SMALL_STATE(102)] = 2196,
  [SMALL_STATE(103)] = 2211,
  [SMALL_STATE(104)] = 2230,
  [SMALL_STATE(105)] = 2249,
  [SMALL_STATE(106)] = 2268,
  [SMALL_STATE(107)] = 2283,
  [SMALL_STATE(108)] = 2298,
  [SMALL_STATE(109)] = 2317,
  [SMALL_STATE(110)] = 2336,
  [SMALL_STATE(111)] = 2355,
  [SMALL_STATE(112)] = 2370,
  [SMALL_STATE(113)] = 2385,
  [SMALL_STATE(114)] = 2402,
  [SMALL_STATE(115)] = 2414,
  [SMALL_STATE(116)] = 2430,
  [SMALL_STATE(117)] = 2444,
  [SMALL_STATE(118)] = 2457,
  [SMALL_STATE(119)] = 2470,
  [SMALL_STATE(120)] = 2481,
  [SMALL_STATE(121)] = 2494,
  [SMALL_STATE(122)] = 2507,
  [SMALL_STATE(123)] = 2520,
  [SMALL_STATE(124)] = 2533,
  [SMALL_STATE(125)] = 2543,
  [SMALL_STATE(126)] = 2553,
  [SMALL_STATE(127)] = 2563,
  [SMALL_STATE(128)] = 2573,
  [SMALL_STATE(129)] = 2583,
  [SMALL_STATE(130)] = 2593,
  [SMALL_STATE(131)] = 2603,
  [SMALL_STATE(132)] = 2613,
  [SMALL_STATE(133)] = 2623,
  [SMALL_STATE(134)] = 2633,
  [SMALL_STATE(135)] = 2643,
  [SMALL_STATE(136)] = 2653,
  [SMALL_STATE(137)] = 2663,
  [SMALL_STATE(138)] = 2673,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(137),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(124),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(137),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(39),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(66),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [40] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(125),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 4), SHIFT_REPEAT(26),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 4),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 4), SHIFT_REPEAT(54),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 4), SHIFT_REPEAT(4),
  [64] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 4), SHIFT_REPEAT(125),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_index, 4),
  [73] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_index, 4),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 5),
  [77] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 5),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 5, .production_id = 8),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 5, .production_id = 8),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__binary_op, 3),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__binary_op, 3),
  [89] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(39),
  [92] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(20),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(4),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2),
  [100] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_list_repeat1, 2), SHIFT_REPEAT(125),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3),
  [105] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3),
  [107] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, .production_id = 8),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 4, .production_id = 8),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 3, .production_id = 3),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 3, .production_id = 3),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_map, 4, .production_id = 3),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_map, 4, .production_id = 3),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 1),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 1),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 4),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 4),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 4),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 4),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_declaration, 2),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_declaration, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 5),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 5),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, .production_id = 11),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, .production_id = 11),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 5, .production_id = 10),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 5, .production_id = 10),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 3, .production_id = 1),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 3, .production_id = 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_call, 4, .production_id = 6),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_call, 4, .production_id = 6),
  [197] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [199] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__type, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_function_call_repeat1, 2, .production_id = 2),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [215] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__map_item, 5, .production_id = 14),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [221] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__map_item, 3, .production_id = 7),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(132),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [229] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [231] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [233] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [235] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 4), SHIFT_REPEAT(28),
  [238] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 4), SHIFT_REPEAT(133),
  [241] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [243] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [249] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pipeline_block_repeat1, 2), SHIFT_REPEAT(132),
  [252] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_block_repeat1, 2),
  [254] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_pipeline_block_repeat1, 2), SHIFT_REPEAT(124),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [267] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_step, 2),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [277] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_map_repeat1, 2, .production_id = 2),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [287] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline_block, 3),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipeline_block, 3),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [297] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_pipeline_block, 4),
  [299] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_pipeline_block, 4),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [309] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_pipeline_block_repeat2, 2), SHIFT_REPEAT(30),
  [312] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_block_repeat2, 2),
  [314] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_pipeline_block_repeat1, 1),
  [316] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_block_repeat1, 1),
  [318] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [326] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_pipeline_block_repeat2, 1),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [330] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [346] = {.entry = {.count = 1, .reusable = false}}, SHIFT(138),
  [348] = {.entry = {.count = 1, .reusable = false}}, SHIFT(128),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [354] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [356] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [358] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [360] = {.entry = {.count = 1, .reusable = false}}, SHIFT(127),
  [362] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2),
  [364] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [366] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_jenkins(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
